name: PR Sanity Check

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install
      - name: Lint
        run: |
          npm run lint
      - name: Build
        run: |
          npx reveal-md lessons/ --static dist
          rsync -a -r lessons/ dist/
